apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:  
      app: hpa-app
  template:
    metadata:
      labels:
        app: hap-app
    spec:
      containers:
      - name: hpa-app
      image: darkxprime/kind-hpa:latest
      ports:
      - containerPort: 3000
      resources:
        requests:
          cpu: "500m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "512Mi"
  
